# Generated by Django 5.0.2 on 2024-03-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=100)),
                ('stoploss', models.FloatField()),
            ],
        ),
    ]
